channels:
- conda-forge
dependencies:
# Jupyter
- jupyterlab
- jupyter-offlinenotebook
- nodejs=16.10.0
- nbconvert
- xeus=2.0.0
# RTC
- jupyterlab-link-share
# Python Kernel
- ipykernel=6.4.1
- xeus-python=0.13.0
- ipywidgets=7.6.3
- widgetsnbextension=3.5.1
- ipyleaflet=0.14.0
- altair=4.1.0
- bqplot=0.12.30
- dask=2021.9.1
- matplotlib=3.4.3
- pandas=1.3.3
- python=3.7.10
- scikit-image=0.18.3
- scikit-learn=1.0
- seaborn=0.11.2
- tensorflow=2.6
- sympy=1.8
- pyyaml=5.4.1
- traittypes=0.2.1
- invoke=1.6.0
# C++ Kernel
- xeus-cling=0.13.0
- xtensor=0.23.10
- xtensor-blas=0.19.1
- xwidgets=0.26.0
- xleaflet=0.16.0