channels:
- conda-forge
dependencies:
# Jupyter
- jupyterlab=3.1
- jupyter-offlinenotebook=0.2
- nodejs=12
- nbconvert=6
# RTC
- jupyterlab-link-share=0.2
# Python Kernel
- ipykernel=5.1
- xeus-python=0.13.0
- ipywidgets=7.6
- widgetsnbextension=3.5
- ipyleaflet=0.14.0
- altair=4.1
- bqplot=0.12.20
- dask=2020.12
- matplotlib=3.1
- pandas=1
- python=3.9
- scikit-image=0.15
- scikit-learn=0.21
- seaborn=0.11
- tensorflow=1.13
- sympy=1.4
- pyyaml
- traittypes==0.2.1
- invoke=1.2
# C++ Kernel
- xeus-cling=0.13.0
- xtensor=0.23.0
- xtensor-blas=0.19.0
- xwidgets=0.26.0
- xleaflet=0.16