channels:
- conda-forge
dependencies:
# Jupyter
- jupyterlab
- jupyter-offlinenotebook
- nodejs
- nbconvert
- xeus
# RTC
- jupyterlab-link-share
# Python Kernel
- ipykernel
- xeus-python
- ipywidgets
- widgetsnbextension
- ipyleaflet
- altair
- bqplot
- dask
- matplotlib
- pandas
- python
- scikit-image
- scikit-learn
- seaborn
- tensorflow
- sympy
- pyyaml
- traittypes
- invoke
# C++ Kernel
- xeus-cling=0.13.0
- xtensor
- xtensor-blas
- xwidgets=0.26.0
- xleaflet